app/controllers/afl_controller.py
from flask import render_template, Blueprint, request, redirect, flash, url_for, Response, stream_with_context
from app.services.afl_service import AFLService
from app.services.report_service import ReportService
from app.services.upload_service import UploadService
from app.services.replay_service import ReplayService
from app.Repository.fuzz_target_repository import FuzzTargetRepository

bp = Blueprint('afl_controller', __name__)


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'GET':
        return render_template('upload.html')
    file = request.files['file']
    is_input_by_file = request.form.get('isInputByFile') == 'on'
    if file:
        result = uploadService.upload_fuzz_Target(file, is_input_by_file)
        if result:
            flash(f'{file.filename} 上傳成功')
        else:
            flash(f'{file.filename} 上傳失敗')
    return redirect(url_for('afl_controller.upload'))


@bp.route('/observe', methods=['GET', 'POST'])
def observe():
    return render_template('observe.html')


@bp.route('/reports', methods=['GET'])
def reports():
    target_names = reportService.get_target_names()
    current_target_name = aflService.current_running_target_name()
    return render_template('reports.html', targetNames=target_names, currentTargetName=current_target_name)


@bp.route('/reports/<targetName>', methods=['GET'])
def target_report(targetName):
    target_report = reportService.get_target_report(targetName)
    target_report_img_path = reportService.get_target_report_img_path(
        targetName)
    return render_template('target_report.html', target=targetName, targetResult=target_report, imgs=target_report_img_path)


@bp.route('/replay', methods=['GET'])
def replay():
    target_name = request.args.get('targetName')
    crash_id = request.args.get('crashId')
    target_report_content = replayService.replay_target(
        target_name, crash_id)
    return render_template('replay.html', targetName=target_name, crash=crash_id, htmlContent=target_report_content)


@bp.route('/execute', methods=['POST'])
def execute():
    target_name = request.form.get('targetName')
    aflService.start_running_target(target_name)
    return redirect(url_for('afl_controller.observe'))


@bp.route('/delete', methods=['POST'])
def delete():
    delete_target_list = request.get_json()
    aflService.delete_target(delete_target_list)
    return redirect(url_for('afl_controller.reports'))


@bp.route('/stop', methods=['POST'])
def stop():
    aflService.stop_running_target()
    return redirect(url_for('afl_controller.reports'))


fuzzTargetRepository = FuzzTargetRepository()
aflService = AFLService(fuzzTargetRepository)
uploadService = UploadService(fuzzTargetRepository)
reportService = ReportService(fuzzTargetRepository)
replayService = ReplayService(fuzzTargetRepository)

app/templates/ObservePage.html
{% extends 'base.html' %}

{% block title %}Observe page{% endblock %}

{% block content %}
    <h1 style="padding-top: 50px;">Observe Page</h1>

    <body>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p><br>
                {% endfor %}
            {% endif %}
        {% endwith %}
        
        <table>
            <tr>
                <th>名稱</th>
                <th style="min-width: 400px;">正在執行</th>
                <th>查看詳細狀態</th>
                <th style="min-width: 200px;">執行</th>
            </tr>
            </tr>
            {% for targetName in targetNames %}
                <tr>
                    <td>{{ targetName }}</td>
                    <td style="min-width: 500px; text-align: center;">{% if targetName == currentTargetName %}是{% endif %}</td>
                    <td><a href="/target/{{ targetName }}">查看詳細狀態</a></td>
                    <td style="min-width: 200px; text-align: center;">
                        <form method="POST" action="/execute">
                            <input type="hidden" name="targetName" value="{{ targetName }}">
                            <button type="submit" style="min-width: 100px; min-height: 50px;">執行</button>
                        </form>
                    </td>
                </tr>
                </tr>
            {% endfor %}
        </table>

        </form>
    </body>

{% endblock %}

app/templates/UploadPage.html
{% extends 'base.html' %}

{% block title %}Upload page{% endblock %}

{% block content %}
    <h1 style="padding-top: 50px;">Upload Page</h1>

    <body>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p><br>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <p>上傳檔案</p>
        <form action="{{ url_for('afl_controller.upload') }}" method="post" enctype="multipart/form-data">
            <label for="duration" style="font-size: smaller;">執行時間:</label>
            <select name="duration" id="duration">
                <option value="1">1hr</option>
                <option value="3">3hr</option>
                <option value="6">6hr</option>
                <option value="24">24hr</option>
            </select>
            <br>
            <input type="file" name="file">
            <input type="submit" value="上傳">
        </form>
    </body>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}AFL GUI Tool{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <div id="navbar">
        <a href="{{ url_for('afl_controller.index') }}">首頁</a>
        <a href="{{ url_for('afl_controller.upload') }}">上傳待測程式</a>
        <a href="{{ url_for('afl_controller.reports') }}">檢視待測程式</a>
        <a href="{{ url_for('afl_controller.observe') }}">觀看待測程式</a>
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>AFL GUI TOOL</h1>
    <p>歡迎來到測試自動化系統！</p>
    <p>請選擇您要進行的操作。</p>
{% endblock %}

app/templates/observe.html
{% extends 'base.html' %}

{% block title %}Observe page{% endblock %}

{% block content %}
    <div class="iframe-container">
        <div style="transform: scale(1.3); width: 650px; height: 400px; pointer-events: none; padding-top: 70px;">
            <iframe style="transform: scale(1.3);  width:650px; height:400px;" id="ttyd-iframe" src="http://localhost:5001/" ></iframe>
        </div>
    </div>
    <script>
        window.onload = function() {
            var iframe = document.getElementById('ttyd-iframe');
            iframe.onload = function() {
                iframe.contentWindow.onbeforeunload = null;
            };
        };
    </script>
{% endblock %}

app/templates/replay.html
{% extends 'base.html' %}

{% block title %}Replay page{% endblock %}

{% block content %}
    <h1>Replay target {{ targetName }} for crash Id {{ crash }}</h1>
    <p>If not showing the crash replay result, you can refresh the page again.</p>
    <div class="terminal-output">
        {{ htmlContent|safe }}
    </div>
{% endblock %}

app/templates/reports.html
{% extends 'base.html' %}

{% block title %}Reports page{% endblock %}

{% block content %}
    <h1>Reports Page</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p><br>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <button onclick="sendDataToController();">刪除所選目標</button>

    <table>
        <thead>
            <tr>
                <th>選擇</th>
                <th>名稱</th>
                <th>正在執行</th>
                <th>查看詳細狀態</th>
                <th>執行</th>
                <th>中止</th>
            </tr>
        </thead>
        <tbody>
            {% for targetName in targetNames %}
                <tr>
                    <td>
                        <input type="checkbox" name="target" value="{{ targetName }}">
                    </td>
                    <td>{{ targetName }}</td>
                    <td>{% if targetName == currentTargetName %}是{% endif %}</td>
                    <td>
                        <form method="get" action="/reports/{{ targetName }}">
                            <input type="hidden" name="targetName" value="{{ targetName }}">
                            <button type="submit">查看詳細狀態</button>
                        </form>
                    </td>
                    <td>
                        <form method="POST" action="/execute">
                            <input type="hidden" name="targetName" value="{{ targetName }}">
                            <button type="submit">執行</button>
                        </form>
                    </td>
                    {% if targetName == currentTargetName %}
                    <td>
                        <form method="POST" action="/stop">
                            <input type="hidden" name="targetName" value="{{ targetName }}">
                            <button type="submit">中止</button>
                        </form>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function sendDataToController() {
            var checkboxes = document.getElementsByName("target");
            var selectedValues = [];
            checkboxes.forEach(function(checkbox) {
                if (checkbox.checked) {
                    selectedValues.push(checkbox.value);
                }
            });
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "/delete", true);
            xhr.setRequestHeader("Content-Type", "application/json");
            xhr.send(JSON.stringify(selectedValues));
            xhr.onload = function() {
                if (xhr.status == 200) {
                    location.reload();
                }
            }
        }
    </script>
{% endblock %}

app/templates/target_report.html
{% extends 'base.html' %}

{% block title %}Target report{% endblock %}

{% block content %}
    <h1>Report Page</h1>
    <h2>Target Name: {{ target }}</h2>

    <h2>Fuzz Result: </h2>

    {% if targetResult == None %}
        <p>No report found, maybe the target still not be run.</p>
    {% elif targetResult.num_fuzz_data ==  0%}
        <p>The report will be generated after running for a while.</p>
    {% else %}
        <div>
            {% for img in imgs %}
                <img src="{{ url_for('static', filename= 'fuzz_targets_img/' + target + '/' + img ) }}" alt="Image">
                <br>
            {% endfor %}
        </div>
        <hr>
        <p>Number of crashed found: {{ targetResult.num_crashes }}</p>
        <h3>Crashed Targets List:</h3>
        <ul class="crash-list">
            {% for crashed in targetResult.get_crashed %}
            <li class="crash-item">
                <hr>
                <form method="get" action="/replay" class="replay-form">
                    <input type="hidden" name="targetName" value="{{ target }}">
                    <input type="hidden" name="crashId" value="{{ crashed.get_data.id }}">
                    <button type="submit">Replay</button>
                </form>
                <p><strong>Crash ID:</strong> {{ crashed.get_data.id }}</p>
                <p><strong>Signal Number:</strong> {{ crashed.get_data.signal_number }}</p>
                <p><strong>Relative Time:</strong> {{ crashed.get_data.relative_time }}</p>
                <p><strong>Execs:</strong> {{ crashed.get_data.execs }}</p>
                <p><strong>Crashing Input:</strong> {{ crashed.get_data.crashingInput }}</p>
            </li>
            {% endfor %}
        </ul>
        
    {% endif %}
{% endblock %}

app/templates/upload.html
{% extends 'base.html' %}

{% block title %}Upload page{% endblock %}

{% block content %}
    <h1 style="padding-top: 50px;">Upload Page</h1>

    <body>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p><br>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <p>上傳檔案</p>
        <form action="{{ url_for('afl_controller.upload') }}" method="post" enctype="multipart/form-data">
            <label for="isInputByFile">使用文件作為輸入:</label>
            <input type="checkbox" name="isInputByFile" id="isInputByFile">
            <br>
            <input type="file" name="file">
            <input type="submit" value="上傳">
        </form>
    </body>

{% endblock %}